### ISSUE TITLE
Critical CVE fixes

### ISSUE THREAD

**Issue by SatanicMechanic** [tetratelabs/istio#1008]
There are [several outstanding vulnerabilities](https://istio.io/latest/news/security/istio-security-2022-005/) that have not yet been addressed in in this version.  What is the ETA for these fixes?

**Comment by psbrar99** [comment]
@SatanicMechanic : Thanks for bringing this up. You can download the 1.12.8 and 1.13.5 tetrate and tetratefips  patch releases which address these CVE's.
https://preliminary.istio.io/latest/news/releases/1.13.x/announcing-1.13.5/
https://preliminary.istio.io/latest/news/releases/1.12.x/announcing-1.12.8/

**Comment by SatanicMechanic** [comment]
Thanks for the response, but I'm not seeing the tetrate fips version in your links.

**Comment by psbrar99** [comment]
You can use getmesh cli to list, fetch and install istio fips versions.
More details are [here](https://istio.tetratelabs.io/getmesh-cli/).

This the tag <1.12.8-tetratefips-v0-distroless,1.13.5-tetratefips-v0-distroless> to download images from registry. 

```
➜  getmesh git:(1.12.8) getmesh list
ISTIO VERSION	  FLAVOR   	FLAVOR VERSION	   K8S VERSIONS
   *1.13.5   	  tetrate  	      0       	1.20,1.21,1.22,1.23
   1.13.5    	tetratefips	      0       	1.20,1.21,1.22,1.23
   1.13.5    	   istio   	      0       	1.20,1.21,1.22,1.23
   1.13.3    	  tetrate  	      0       	1.20,1.21,1.22,1.23
   1.13.3    	tetratefips	      0       	1.20,1.21,1.22,1.23
   1.13.3    	   istio   	      0       	1.20,1.21,1.22,1.23
   1.13.2    	  tetrate  	      0       	1.20,1.21,1.22,1.23
   1.13.2    	tetratefips	      0       	1.20,1.21,1.22,1.23
   1.13.2    	   istio   	      0       	1.20,1.21,1.22,1.23
   1.12.8    	  tetrate  	      0       	1.19,1.20,1.21,1.22
   1.12.8    	tetratefips	      0       	1.19,1.20,1.21,1.22
   1.12.8    	   istio   	      0       	1.19,1.20,1.21,1.22
```
